services:
  user_service_db:
    container_name: 'user_service_db'
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: 'user_service'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data