services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'table_service'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db-data:/var/lib/mysql